services:
  virtuoso:
    ports:
      - "8890:8890"
  nats:
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./config/nats/nats-server-dev.conf:/nats-config/nats.conf
  mongo-express:
    image: mongo-express
    networks:
      swarm:
    restart: "no"
    env_file:
      - ./config/env-files/dev/express.env
    ports:
      - "8081:8081"
  mongo:
    ports:
      - "27017:27017"
    env_file:
      - ./config/env-files/dev/mongo.env
  migrations:
    volumes:
      - ./config/dev-migrations:/migrations/dev
    env_file:
      - ./config/env-files/dev/mongo_cli.env
  job-manager:
    image: nbittich/job-manager:latest
    # ports:
    #   - "8080:80"
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/mongo_cli.env
      - ./config/env-files/dev/sparql_cli.env
      - ./config/env-files/dev/api.env
      - ./config/env-files/dev/download.env
      - ./config/env-files/dev/job-manager.env
  crawler:
    image: nbittich/crawler:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/crawler.env
      # - ./config/env-files/dev/mongo_cli.env
  extractor:
    image: nbittich/extractor:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/extractor.env
  filter:
    image: nbittich/filter:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/filter.env
  add-uuid:
    image: nbittich/add-uuid:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/mongo_cli.env
      - ./config/env-files/dev/add-uuid.env
  diff:
    image: nbittich/diff:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/mongo_cli.env
      - ./config/env-files/dev/diff.env
  publish:
    image: nbittich/publish:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/sparql_cli.env
      - ./config/env-files/dev/publish.env
  cleanup:
    image: nbittich/cleanup:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/mongo_cli.env
      - ./config/env-files/dev/cleanup.env
  archive:
    image: nbittich/archive:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/mongo_cli.env
      - ./config/env-files/dev/archive.env
  index:
    image: nbittich/index:latest
    env_file:
      - ./config/env-files/dev/nats.env
      - ./config/env-files/dev/sparql_cli.env
      - ./config/env-files/dev/index.env
  frontend:
    image: nbittich/swarm-frontend:latest
    env_file:
      - ./config/env-files/dev/frontend.env
  proxy:
    image: nginx:1.28-alpine
    networks:
      swarm:
    volumes:
      - ./config/proxy/http:/etc/nginx/conf.d
      - ./config/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/proxy/templates:/etc/nginx/templates:ro
    env_file:
      - ./config/env-files/dev/download.env
    ports:
      - "8080:80"
    depends_on:
      - job-manager
      - frontend
    restart: always
  meilisearch:
      env_file:
          - ./config/env-files/dev/meilisearch.env
      ports:
          - "7700:7700"
  # dev only!
  meilisearch-dashboard:
      build:
          context: ./docker-files/meilisearch-dashboard/.
      environment:
          REACT_APP_MEILI_SERVER_ADDRESS: http://localhost:7700
      ports:
        - 3000:3000
