services:
  virtuoso:
    image: redpencil/virtuoso:1.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://swarm.bittich.be/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./config/virtuoso/:/opt/virtuoso-scripts
    restart: always
    networks:
      swarm:
  nats:
    image: nats:2.11-alpine
    restart: always
    networks:
      swarm:
    container_name: nats-server
    command: -js -sd /nats-data -c /nats-config/nats.conf
    volumes:
      - ./data/nats/data:/nats-data
      - ./config/nats/nats-server.conf:/nats-config/nats.conf
  mongo:
    image: mongo:7
    networks:
      swarm:
    restart: always
    volumes:
      - ./data/db:/data/db
  migrations:
    image: nbittich/mongodb-migration:v0.3.0
    restart: "no"
    volumes:
      - ./config/migrations:/migrations/all
    networks:
      swarm:
  # app services
  crawler:
    image: nbittich/crawler:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
      - ./data/crawler/cache:/cache
    networks:
      swarm:
  extractor:
    image: nbittich/extractor:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  job-manager:
    image: nbittich/job-manager:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
      - ./config/job-manager/definitions.json:/definitions.json
    networks:
      swarm:
  filter:
    image: nbittich/filter:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
      - ./config/shacl:/config
    networks:
      swarm:
  add-uuid:
    image: nbittich/add-uuid:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  diff:
    image: nbittich/diff:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  publish:
    image: nbittich/publish:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  cleanup:
    image: nbittich/cleanup:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  archive:
    image: nbittich/archive:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
    networks:
      swarm:
  index:
    image: nbittich/index:0.1.6
    restart: always
    volumes:
      - ./data/shared:/share
      - ./config/index:/index_config
    networks:
      swarm:
  frontend:
    image: nbittich/swarm-frontend:0.1.6
    restart: always
    networks:
      swarm:
  meilisearch:
      image: getmeili/meilisearch:v1
      volumes:
          - ./data/meilisearch:/meili_data
      restart: always
      networks:
          swarm:
networks:
  swarm:
