services:
  job-manager:
    build:
      context: ../swarm
      args:
        CRATE_NAME: job-manager
  crawler:
    build:
      context: ../swarm
      args:
        CRATE_NAME: crawler
  extractor:
    build:
      context: ../swarm
      args:
        CRATE_NAME: extractor
  filter:
    build:
      context: ../swarm/filter/
      args:
        CRATE_NAME: filter
  add-uuid:
    build:
      context: ../swarm
      args:
        CRATE_NAME: add-uuid
  diff:
    build:
      context: ../swarm
      args:
        CRATE_NAME: diff
  publish:
    build:
      context: ../swarm
      args:
        CRATE_NAME: publish
  cleanup:
    build:
      context: ../swarm
      args:
        CRATE_NAME: cleanup
  archive:
    build:
      context: ../swarm
      args:
        CRATE_NAME: archive
  index:
    build:
      context: ../swarm
      args:
        CRATE_NAME: index
  frontend:
    build:
      context: ../swarm/frontend/
